version: '3.9'
services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
  



